#!/usr/bin/env bash
# configures a server to listening on port 80 of all servers active IPv4 IPs
apt update
apt install -y nginx
sed -i 's/add_header X-Served-By .*/add_header X-Served-By "myserver";/g' /etc/nginx/sites-available/default
nginx -t
nginx -g "daemon off;"
