#!/usr/bin/env bash
# configures a server to listening on port 80 of all servers active IPv4 IPs
sed -i 's/add_header X-Served-By .*/add_header X-Served-By "myserver";/g' /etc/nginx/sites-available/default
sudo service nginx restart
echo "" | sudo dd status=none of=/run/nginx.pid
