#!/usr/bin/env bash
# Define the function to handle signals
# Trap signals and call the signal_handler function
# Get the PID of the current process and store it in the file /var/run/myscript.pid
# Display "To infinity and beyond" indefinitely

terminator() {
	rm /var/run/myscript.pid
	exit
}

echo "$$" > /var/run/myscript.pid

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'echo "I hate the kill command" && terminator' SIGTERM
	trap 'terminator' SIGQUIT
done
