#!/usr/bin/env bash
# Function to demonstrate the use of multiple counters

hour=0

while [ $hour -le 12 ]; do
	echo "Hour: $hour"

	minute=1
	while [ $minute -le 59 ]; do
		echo "$minute"
		((minute++))
	done

	((hour++))
done
